"""
pdf_extractor.py — Extract clinical fields from hospital PDF records.

The PDFs are generated by GeneXus and have a two-column layout that causes
PyPDF2 to extract text in a non-obvious order. Field values sometimes appear
BEFORE their labels. This module handles both orderings.
"""

import re
import PyPDF2


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def extract_fields(pdf_path):
    """
    Extract all required fields from a clinical PDF.

    Returns a dict with keys:
        especie, sexo, edad, raza, peso_grs, peso_kg, tamano,
        departamento, paraje, especialidad, motivo_consulta, examen_objetivo

    All values are str or None. tamano is only set for CANINO CRUZA.
    """
    text_p1, text_p2 = _read_pages(pdf_path)
    if text_p1 is None:
        return _empty_record()

    fields = {}

    # --- From page 1 ---
    especie, raza = _extract_especie_raza(text_p1)
    fields['especie']       = especie
    fields['raza']          = raza
    fields['sexo']          = _extract_sexo(text_p1)
    fields['edad']          = _extract_edad(text_p1)
    fields['peso_grs']      = _extract_peso(text_p1)
    fields['departamento']  = _extract_departamento(text_p1)
    fields['paraje']        = _extract_paraje(text_p1)
    fields['especialidad']  = _extract_especialidad(text_p1)
    fields['motivo_consulta'] = _extract_motivo(text_p1)

    # --- From page 2 ---
    fields['examen_objetivo'] = _extract_examen(text_p2) if text_p2 else None

    # --- Derived fields ---
    fields['peso_kg'] = _grs_to_kg(fields['peso_grs'])
    fields['tamano']  = _clasificar_tamano(especie, raza, fields['peso_kg'])

    return fields


def is_data_complete(fields):
    """
    Return True if both motivo_consulta and examen_objetivo are non-empty.
    Used to decide whether to try the next (older) consultation.
    """
    def _has(val):
        return bool(val and val.strip())
    return _has(fields.get('motivo_consulta')) and _has(fields.get('examen_objetivo'))


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _read_pages(pdf_path):
    """Return (page1_text, page2_text). Either may be None on error."""
    try:
        with open(pdf_path, 'rb') as f:
            reader = PyPDF2.PdfReader(f)
            p1 = reader.pages[0].extract_text() if len(reader.pages) > 0 else None
            p2 = reader.pages[1].extract_text() if len(reader.pages) > 1 else None
        return p1, p2
    except Exception as e:
        print(f'[pdf_extractor] Error reading {pdf_path}: {e}')
        return None, None


def _empty_record():
    keys = ['especie','raza','sexo','edad','peso_grs','peso_kg',
            'tamano','departamento','paraje','especialidad',
            'motivo_consulta','examen_objetivo']
    return {k: None for k in keys}


# --- Especie + Raza ---

def _extract_especie_raza(text):
    """
    Two possible orderings in the extracted text:
      1. value-before-label:  "CANINO CANICHE Especie Raza"
      2. label-before-value:  "Especie FELINA Raza CRUZA FELIN"
    """
    # Pattern 1: value before label
    m = re.search(
        r'(CANINO|FELINO|FELINA)\s+(.+?)\s+Especie\s+Raza',
        text, re.IGNORECASE
    )
    if m:
        especie = m.group(1).upper()
        raza = m.group(2).strip().upper()
        especie = 'FELINO' if especie == 'FELINA' else especie
        return especie, raza

    # Pattern 2: label before value
    m = re.search(
        r'Especie\s+(CANINO|FELINO|FELINA)\s+Raza\s+(.+?)(?:\n|$)',
        text, re.IGNORECASE
    )
    if m:
        especie = m.group(1).upper()
        raza = m.group(2).strip().upper()
        especie = 'FELINO' if especie == 'FELINA' else especie
        return especie, raza

    return None, None


# --- Sexo ---

def _extract_sexo(text):
    """
    The sex letter (M/H) appears between the birth date and 'Nro:'.
    e.g. "20/07/22 MNro:" or "01/01/18 HNro:"
    Also handle spaced variants: "20/07/22 M Nro:"
    """
    m = re.search(r'\d{2}/\d{2}/\d{2,4}\s+([MHmh])\s*Nro:', text)
    if m:
        return m.group(1).upper()
    return None


# --- Edad ---

def _extract_edad(text):
    """Edad field is always in years (integer). "Edad: 0" or "Edad: 6"."""
    m = re.search(r'Edad:\s*(\d+)', text)
    return int(m.group(1)) if m else None


# --- Peso ---

def _extract_peso(text):
    """
    Two possible orderings:
      1. value before label: "0,000 Peso (grs.)"
      2. label before value: "Peso (grs.) 3,300"
    Returns raw string value (e.g. "3,300") or None.
    """
    # Pattern 1: value before label
    m = re.search(r'([\d]+[,\.][\d]+)\s+Peso\s*\(grs\.\)', text)
    if m:
        return m.group(1)

    # Pattern 2: label before value
    m = re.search(r'Peso\s*\(grs\.\)\s*([\d]+[,\.][\d]+)', text)
    if m:
        return m.group(1)

    return None


# --- Departamento ---

def _extract_departamento(text):
    """
    Two possible orderings on the same line as Paraje/Sec:
      1. value before label: "24 CERRO Sec: Paraje: Departamento MONTEVIDEO"
      2. label before value: "Departamento MONTEVIDEO Sec: 11 Paraje: BUCEO"
    """
    # Pattern 2 (label before value) — solo en la misma línea
    m = re.search(r'Departamento[ \t]+([A-ZÁÉÍÓÚÜÑ]+)', text)
    if m:
        return m.group(1).strip()

    return None


# --- Paraje ---

def _extract_paraje(text):
    """
    Two possible orderings:
      1. value before label: "24 CERRO Sec: Paraje: Departamento MONTEVIDEO"
         → paraje = "24 CERRO"
      2. label before value: "Departamento MONTEVIDEO Sec: 11 Paraje: BUCEO"
         → paraje = "BUCEO"
    Falls back to Dirección field if paraje is empty.
    """
    # Pattern 1: value before label — "11 BUCEO Sec: Paraje: Departamento MONTEVIDEO"
    # Format is: "[SEC_NUM] PARAJE Sec: Paraje: Departamento DEP"
    # Leading number is the sector — we skip it to get just the paraje name.
    m = re.search(r'\n(?:\d+\s+)?(.+?)\s+Sec:\s+Paraje:\s+Departamento', text)
    if m:
        val = m.group(1).strip()
        if val:
            return val

    # Pattern 2: label before value — "Paraje: BUCEO"
    # Guard: don't match if the value starts with "Departamento"
    m = re.search(r'Paraje:\s+(.+?)(?:\n|$)', text)
    if m:
        val = m.group(1).strip()
        if val and not val.upper().startswith('DEPARTAMENTO'):
            return val

    # Fallback: la dirección aparece antes de la fecha de ingreso y el número de cliente
    # e.g. "BLVAR. ARTIGAS 34/301.14/11/16 0000049981"
    m = re.search(r'([A-ZÁÉÍÓÚÜÑ][^\n]+?)\d{2}/\d{2}/\d{2,4}\s+\d{7,}', text)
    if m:
        val = m.group(1).strip()
        if len(val) >= 3:
            return val

    return None


# --- Especialidad ---

def _extract_especialidad(text):
    """
    The value appears between "Motivo Consulta:" and "Especialidad:".
    e.g. "Motivo Consulta:Medicina General Especialidad:"
    """
    m = re.search(r'Motivo Consulta:\s*(.+?)\s*Especialidad:', text)
    if m:
        return m.group(1).strip()
    return None


# --- Motivo Consulta ---

def _extract_motivo(text):
    """
    The motivo text is located between the Peso (grs.) line and ANAMNESIS.
    It follows the Edad/Peso row in the extracted text.
    """
    # Find text between end of "Peso (grs.)" token and "ANAMNESIS"
    m = re.search(
        r'Peso\s*\(grs\.\)[^\n]*\n(.+?)\nANAMNESIS',
        text, re.DOTALL
    )
    if m:
        val = m.group(1).strip()
        return val if val else None

    return None


# --- Examen Objetivo Particular ---

def _extract_examen(text):
    """
    Located in page 2 between "Examen Objetivo Particular" and "DIAGNOSTICO".
    The word "Pulso" may appear immediately after the label (layout artifact).
    """
    m = re.search(
        r'Examen Objetivo Particular[^\n]*\n(.+?)\nDIAGNOSTICO',
        text, re.DOTALL
    )
    if m:
        val = m.group(1).strip()
        return val if val else None

    return None


# --- Derived ---

def _grs_to_kg(peso_str):
    """Convert "3,300" or "3.300" → 3.3 (kg). Returns float or None."""
    if not peso_str:
        return None
    try:
        # Comma is thousands separator: "3,300" = 3300 grams = 3.3 kg
        normalized = peso_str.replace(',', '')
        grs = float(normalized)
        return round(grs / 1000, 3)
    except ValueError:
        return None


def _clasificar_tamano(especie, raza, peso_kg):
    """
    Only for CANINO CRUZA. Returns 'chico', 'mediano', 'grande', or None.
    """
    if especie != 'CANINO':
        return None
    if not raza or 'CRUZA' not in raza.upper():
        return None
    if peso_kg is None:
        return None
    if peso_kg <= 10:
        return 'chico'
    elif peso_kg <= 20:
        return 'mediano'
    else:
        return 'grande'
